### ISSUE TITLE
Audit React Hooks course for language/grammar

### ISSUE THREAD

**Issue by SheaBelsky** [wayfair/awesome-learning-exercises#30]
We'd like to make sure that our React Hooks course has proper English grammar, spelling, and language throughout the exercise. Content should be readable and understandable to everyone, especially for individuals for whom English may not be their strongest language.

**Comment by florenciasilva** [comment]
Hey 👋 I would love to work on this!

**Comment by Cooperbuilt** [comment]
It's all yours!

**Comment by Cooperbuilt** [comment]
Closing
